/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionsHandleRouteImport } from './routes/collections/$handle'
import { Route as PagesHandleRouteImport } from './routes/pages/$handle'
import { Route as PoliciesTypeRouteImport } from './routes/policies/$type'
import { Route as ProductsHandleRouteImport } from './routes/products/$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => CollectionsRoute,
} as any)
const PagesHandleRoute = PagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTypeRoute = PoliciesTypeRouteImport.update({
  id: '/policies/$type',
  path: '/policies/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$handle': typeof PagesHandleRoute
  '/policies/$type': typeof PoliciesTypeRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$handle': typeof PagesHandleRoute
  '/policies/$type': typeof PoliciesTypeRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-sellers': typeof BestSellersRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$handle': typeof PagesHandleRoute
  '/policies/$type': typeof PoliciesTypeRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-sellers'
    | '/collections'
    | '/shop'
    | '/collections/$handle'
    | '/pages/$handle'
    | '/policies/$type'
    | '/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-sellers'
    | '/collections'
    | '/shop'
    | '/collections/$handle'
    | '/pages/$handle'
    | '/policies/$type'
    | '/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/best-sellers'
    | '/collections'
    | '/shop'
    | '/collections/$handle'
    | '/pages/$handle'
    | '/policies/$type'
    | '/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestSellersRoute: typeof BestSellersRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ShopRoute: typeof ShopRoute
  PagesHandleRoute: typeof PagesHandleRoute
  PoliciesTypeRoute: typeof PoliciesTypeRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/pages/$handle': {
      id: '/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/pages/$handle'
      preLoaderRoute: typeof PagesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$type': {
      id: '/policies/$type'
      path: '/policies/$type'
      fullPath: '/policies/$type'
      preLoaderRoute: typeof PoliciesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsHandleRoute: typeof CollectionsHandleRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsHandleRoute: CollectionsHandleRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestSellersRoute: BestSellersRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ShopRoute: ShopRoute,
  PagesHandleRoute: PagesHandleRoute,
  PoliciesTypeRoute: PoliciesTypeRoute,
  ProductsHandleRoute: ProductsHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
